create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 100),
  email text not null check (char_length(email) between 5 and 200),
  message text not null check (char_length(message) between 5 and 3000),
  created_at timestamptz not null default now()
);

alter table public.contact_requests enable row level security;

create policy "allow public contact form inserts"
on public.contact_requests
for insert
to anon
with check (true);

revoke all on table public.contact_requests from anon;
grant insert on table public.contact_requests to anon;

create table if not exists public.lead_magnet_requests (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 100),
  email text not null check (char_length(email) between 5 and 200),
  resource_slug text not null check (char_length(resource_slug) between 2 and 120),
  landing_path text not null check (char_length(landing_path) between 1 and 300),
  referrer text not null default '' check (char_length(referrer) <= 500),
  source text not null default '' check (char_length(source) <= 120),
  medium text not null default '' check (char_length(medium) <= 120),
  campaign text not null default '' check (char_length(campaign) <= 180),
  content text not null default '' check (char_length(content) <= 180),
  term text not null default '' check (char_length(term) <= 180),
  created_at timestamptz not null default now()
);

alter table public.lead_magnet_requests enable row level security;

create policy "allow public lead magnet inserts"
on public.lead_magnet_requests
for insert
to anon
with check (true);

revoke all on table public.lead_magnet_requests from anon;
grant insert on table public.lead_magnet_requests to anon;

create table if not exists public.workbook_responses (
  id uuid primary key,
  name text not null check (char_length(name) between 2 and 100),
  email text not null check (char_length(email) between 5 and 200),
  answers jsonb not null check (jsonb_typeof(answers) = 'object'),
  privacy_accepted_at timestamptz not null,
  landing_path text not null default '/cambia-direzione/' check (char_length(landing_path) between 1 and 300),
  referrer text not null default '' check (char_length(referrer) <= 500),
  source text not null default '' check (char_length(source) <= 120),
  medium text not null default '' check (char_length(medium) <= 120),
  campaign text not null default '' check (char_length(campaign) <= 180),
  content text not null default '' check (char_length(content) <= 180),
  term text not null default '' check (char_length(term) <= 180),
  user_agent text not null default '' check (char_length(user_agent) <= 500),
  delivered_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.workbook_responses enable row level security;

-- Il workbook passa soltanto dalla funzione server protetta. Il browser non ha
-- permessi diretti di lettura, inserimento, modifica o cancellazione.
revoke all on table public.workbook_responses from anon, authenticated;
