create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 100),
  email text not null check (char_length(email) between 5 and 200),
  message text not null check (char_length(message) between 5 and 3000),
  created_at timestamptz not null default now()
);

alter table public.contact_requests enable row level security;

create policy "allow public contact form inserts"
on public.contact_requests
for insert
to anon
with check (true);

revoke all on table public.contact_requests from anon;
grant insert on table public.contact_requests to anon;
