import React, { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowLeft, ArrowRight, Check, LockKeyhole, Mail, RotateCcw, Save, Send } from 'lucide-react'
import { LandingBrand, PRIVACY_URL, useLandingMeta } from './LandingPage'
import { professionalWheel, SESSION_WORKBOOK_PATH, sessionQuestions } from './sessionWorkbookData'
import './workbook.css'
import './session-workbook.css'

const STORAGE_KEY = 'ria-session-workbook-v1'
const LAST_STEP = sessionQuestions.length + 2
const emptyState = () => ({ submissionId: crypto.randomUUID(), name: '', email: '', privacyAccepted: false, company: '', answers: Object.fromEntries(sessionQuestions.map(({ id }) => [id, ''])), wheel: Object.fromEntries(professionalWheel.map(({ id }) => [id, ''])), step: 0 })
const loadState = () => { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); return saved?.submissionId ? { ...emptyState(), ...saved } : emptyState() } catch { return emptyState() } }
const firstName = (name) => name.trim().split(/\s+/)[0] || ''

function WheelChart({ values }) {
  const center = 160; const radius = 118
  const point = (index, value = 10) => { const angle = (-90 + index * 45) * Math.PI / 180; const distance = radius * Number(value || 0) / 10; return `${center + Math.cos(angle) * distance},${center + Math.sin(angle) * distance}` }
  const polygon = professionalWheel.map((_, index) => point(index, values[professionalWheel[index].id])).join(' ')
  return <svg className="sessionWheelSvg" viewBox="0 0 320 320" role="img" aria-label="Ruota del lavoro digitale colorata in base ai voti scelti">
    {professionalWheel.map((item, index) => <path key={item.id} d={`M160 160 L${point(index)} L${point((index + 1) % 8)} Z`} fill={item.color} opacity=".22" />)}
    {[2, 4, 6, 8, 10].map((level) => <polygon key={level} points={professionalWheel.map((_, index) => point(index, level)).join(' ')} fill="none" stroke="#b9b7ae" strokeWidth="1" />)}
    {professionalWheel.map((item, index) => <line key={item.id} x1="160" y1="160" x2={point(index).split(',')[0]} y2={point(index).split(',')[1]} stroke="#c7c3b8" />)}
    <polygon points={polygon} fill="#6455cf" fillOpacity=".36" stroke="#32248e" strokeWidth="3" strokeLinejoin="round" />
    {professionalWheel.map((item, index) => { const [cx, cy] = point(index, values[item.id]); return <circle key={item.id} cx={cx} cy={cy} r="5" fill={item.color} stroke="#101716" strokeWidth="2" /> })}
  </svg>
}

export function SessionWorkbookPage() {
  const [state, setState] = useState(loadState); const [errors, setErrors] = useState({}); const [sending, setSending] = useState(false); const mainRef = useRef(null)
  const step = Math.min(Math.max(state.step, 0), LAST_STEP)
  const question = step > 0 && step <= sessionQuestions.length ? sessionQuestions[step - 1] : null
  const answered = useMemo(() => sessionQuestions.filter(({ id }) => state.answers[id]?.trim()).length, [state.answers])
  useLandingMeta({ title: 'Prima di cambiare: paure, limiti e vincoli | Gabriele Ciandrini', description: 'Workbook riservato per distinguere paure, limiti mentali e vincoli reali e osservare la propria situazione professionale.', robots: 'noindex, follow' })
  useEffect(() => localStorage.setItem(STORAGE_KEY, JSON.stringify({ ...state, step })), [state, step])
  const update = (key, value) => setState((previous) => ({ ...previous, [key]: value }))
  const goTo = (next) => { setErrors({}); setState((previous) => ({ ...previous, step: next })); requestAnimationFrame(() => mainRef.current?.scrollIntoView({ behavior: 'smooth' })) }
  const continueFromIntro = () => { const next = {}; if (state.name.trim().length < 2) next.name = 'Scrivi almeno due caratteri.'; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(state.email.trim())) next.email = 'Inserisci un indirizzo e-mail valido.'; if (!state.privacyAccepted) next.privacy = 'Conferma di aver letto l’informativa.'; setErrors(next); if (!Object.keys(next).length) goTo(1) }
  const submit = async () => { setSending(true); setErrors({}); try { const response = await fetch('/api/session-workbook-submit', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...state, name: state.name.trim(), email: state.email.trim().toLowerCase(), landingPath: SESSION_WORKBOOK_PATH }) }); if (!response.ok) throw new Error(); localStorage.removeItem(STORAGE_KEY); goTo(LAST_STEP) } catch { setSending(false); setErrors({ submit: 'Invio non riuscito. Le risposte sono ancora salvate su questo dispositivo: puoi riprovare senza perdere nulla.' }) } }
  const reset = () => { if (window.confirm('Vuoi cancellare la bozza e ricominciare?')) { localStorage.removeItem(STORAGE_KEY); setState(emptyState()); setErrors({}) } }
  return <div className="onlineWorkbook sessionWorkbook" style={{ '--active-color': question?.color || '#cbff45' }}>
    <header className="workbookHeader"><LandingBrand inverse /><div><button type="button" onClick={reset}><RotateCcw /> Ricomincia</button><a href="/">Esci</a></div></header>
    <div className="sessionProgress"><span style={{ width: `${step / LAST_STEP * 100}%` }} /><small>{step === 0 ? 'INIZIO' : step <= 9 ? `DOMANDA ${step} DI 9` : step === 10 ? 'RUOTA PROFESSIONALE' : step === 11 ? 'RIEPILOGO' : 'COMPLETATO'}</small></div>
    <main ref={mainRef} className="sessionMain">
      {step === 0 && <section className="workbookIntro workbookStepPanel"><p className="workbookKicker"><span>SPAZIO RISERVATO</span> Da usare durante il colloquio</p><h1>Prima di cambiare,<br /><em>guarda cosa ti sta fermando.</em></h1><p className="workbookLead">Non ci sono risposte giuste e nessuna domanda è obbligatoria. Puoi andare avanti, tornare indietro e correggere ciò che hai scritto. La bozza resta su questo dispositivo fino all’invio.</p><div className="workbookIdentityCard"><div className="workbookIdentityHead"><span><LockKeyhole /></span><div><small>IL TUO SPAZIO PERSONALE</small><h2>Dove vuoi ricevere il riepilogo?</h2></div></div><div className="workbookFields"><label><span>Nome</span><input value={state.name} onChange={(event) => update('name', event.target.value)} autoComplete="name" placeholder="Come ti chiami?" />{errors.name && <small className="workbookError">{errors.name}</small>}</label><label><span>E-mail</span><input value={state.email} onChange={(event) => update('email', event.target.value)} type="email" autoComplete="email" placeholder="nome@email.it" />{errors.email && <small className="workbookError">{errors.email}</small>}</label><label className="workbookHoneypot"><span>Azienda</span><input value={state.company} onChange={(event) => update('company', event.target.value)} tabIndex="-1" /></label></div><label className="workbookPrivacy"><input checked={state.privacyAccepted} onChange={(event) => update('privacyAccepted', event.target.checked)} type="checkbox" /><span>Ho letto la <a href={PRIVACY_URL} target="_blank" rel="noreferrer">Privacy Policy</a> e chiedo di ricevere il riepilogo. Non inserirò dati sanitari o particolarmente delicati.</span></label>{errors.privacy && <small className="workbookError workbookPrivacyError">{errors.privacy}</small>}</div><button className="workbookPrimary" type="button" onClick={continueFromIntro}>Inizia <ArrowRight /></button></section>}
      {question && <section className="sessionQuestion workbookStepPanel" style={{ '--section-color': question.color }}><p className="workbookKicker"><span>{question.group}</span> Domanda {step} di 9 · facoltativa</p><h1>{question.text}</h1><textarea autoFocus value={state.answers[question.id]} onChange={(event) => setState((previous) => ({ ...previous, answers: { ...previous.answers, [question.id]: event.target.value } }))} maxLength="2500" placeholder="Scrivi qui, con parole tue…" /><small>{state.answers[question.id].length} / 2500</small></section>}
      {step === 10 && <section className="workbookStepPanel sessionWheel"><p className="workbookKicker"><span>RUOTA PROFESSIONALE</span> Una fotografia, non un giudizio</p><h1>Quanto sei soddisfatto oggi?</h1><p className="workbookLead">Assegna un voto da 0 a 10 a ogni area. La ruota si colora mentre rispondi. Anche questi voti sono facoltativi.</p><div className="sessionWheelLayout"><WheelChart values={state.wheel} /><div className="sessionWheelControls">{professionalWheel.map((item) => <label key={item.id}><span><i style={{ background: item.color }} />{item.label}<strong>{state.wheel[item.id] === '' ? '—' : state.wheel[item.id]}</strong></span><input type="range" min="0" max="10" step="1" value={state.wheel[item.id] === '' ? 0 : state.wheel[item.id]} onChange={(event) => setState((previous) => ({ ...previous, wheel: { ...previous.wheel, [item.id]: event.target.value } }))} aria-label={`${item.label}, voto da 0 a 10`} /></label>)}</div></div></section>}
      {step === 11 && <section className="workbookReview workbookStepPanel"><p className="workbookKicker"><span>RIEPILOGO</span> {answered} risposte su 9</p><h1>{firstName(state.name)}, guarda ciò che <em>hai reso visibile.</em></h1><p className="workbookLead">Puoi tornare su qualsiasi risposta. Quando invii, tu e Gabriele riceverete via e-mail il riepilogo con la ruota professionale.</p><div className="sessionReview">{sessionQuestions.map((item, index) => <button type="button" key={item.id} onClick={() => goTo(index + 1)}><span style={{ background: item.color }}>{index + 1}</span><div><small>{item.group}</small><strong>{item.text}</strong><p>{state.answers[item.id]?.trim() || 'Non compilata'}</p></div></button>)}</div><div className="workbookSendCard"><span className="workbookSendIcon"><Mail /></span><div><small>CONSEGNA PERSONALE</small><h2>Invia il riepilogo a {state.email}</h2><p>Riceverai le risposte e la tua ruota. La bozza viene cancellata dal telefono soltanto dopo l’invio riuscito.</p></div><button className="workbookPrimary" type="button" onClick={submit} disabled={sending}>{sending ? 'Invio in corso…' : 'Invia il riepilogo'} <Send /></button></div>{errors.submit && <p className="workbookSubmitError">{errors.submit}</p>}</section>}
      {step === LAST_STEP && <section className="workbookReview workbookStepPanel sessionComplete"><p className="workbookKicker"><span>COMPLETATO</span> Riepilogo inviato</p><h1>Il tuo punto di partenza <em>ora è più visibile.</em></h1><p className="workbookLead">Controlla la tua e-mail. Troverai il PDF con le risposte e la ruota professionale.</p><div className="sessionCtas"><a className="workbookPrimary" href="/proposta-percorso/">Scopri il percorso Respira. Immagina. Agisci. <ArrowRight /></a><a href="/metodo-respira-immagina-agisci/">Conosci il metodo</a></div></section>}
    </main>
    {step > 0 && step <= 10 && <nav className="workbookNavigation sessionNavigation"><button type="button" onClick={() => goTo(step - 1)}><ArrowLeft /> Indietro</button><div><span><Save /> Salvataggio automatico</span><button className="workbookPrimary" type="button" onClick={() => goTo(step + 1)}>{step === 10 ? 'Rivedi tutto' : 'Avanti'} <ArrowRight /></button></div></nav>}
    {step === 11 && <nav className="workbookNavigation sessionNavigation"><button type="button" onClick={() => goTo(10)}><ArrowLeft /> Torna alla ruota</button><span /></nav>}
    <footer className="sessionFooter"><span>Respira. Immagina. Agisci.</span><div><a href="/proposta-percorso/">La proposta</a><a href="/metodo-respira-immagina-agisci/">Il metodo</a><a href={PRIVACY_URL}>Privacy</a></div></footer>
  </div>
}
