import React, { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowDown, ArrowLeft, ArrowRight, Check, Compass, Link2, LockKeyhole, Mail, RotateCcw, Save, Send, Sparkles } from 'lucide-react'
import { LandingBrand, PRIVACY_URL, useLandingMeta } from './LandingPage'
import { VALUES_GOAL_PATH, desireQuestions, ecologyQuestions, goalQuestions, solidityQuestions, valueColors } from './valuesGoalData'
import './values-goal.css'

const STORAGE_KEY = 'ria-values-goal-v1'
const compatibilityOptions = ['È compatibile', 'È compatibile con alcune condizioni', 'È in conflitto', 'Non ho ancora abbastanza informazioni']
const commonEnds = { famiglia: 'appartenenza', denaro: 'serenità', lavoro: 'realizzazione', carriera: 'realizzazione', salute: 'benessere', libertà: 'libertà', sicurezza: 'serenità', crescita: 'crescita', successo: 'realizzazione', relazioni: 'appartenenza' }
const blankValue = (index) => ({ source: '', meaning: '', allows: '', deeper: '', final: '', importance: 8, presence: 5, workPresence: 4, color: valueColors[index], origin: [] })
const emptyState = () => ({ submissionId: crypto.randomUUID(), name: '', email: '', privacyAccepted: false, company: '', values: Array.from({ length: 5 }, (_, index) => blankValue(index)), order: [0, 1, 2, 3, 4], comparisons: {}, desire: {}, compatibility: {}, conditions: { must: '', negotiable: '', refuse: '', verify: '' }, ecology: {}, goal: {}, solidity: {}, improve: {}, step: 0 })
const loadState = () => { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); return saved?.submissionId ? { ...emptyState(), ...saved } : emptyState() } catch { return emptyState() } }
const cleanWord = (value) => value.trim().toLocaleLowerCase('it-IT')
const firstName = (name) => name.trim().split(/\s+/)[0] || ''

const buildSteps = () => {
  const steps = [{ id: 'intro', kind: 'intro', phase: 'Immagina' }, { id: 'sources', kind: 'sources', phase: 'Radici' }]
  for (let i = 0; i < 5; i += 1) {
    steps.push(
      { id: `meaning-${i}`, kind: 'valueText', field: 'meaning', valueIndex: i, phase: 'Radici', question: (v) => `Che cosa significa per te ${v.source || 'questo elemento'}?` },
      { id: `allows-${i}`, kind: 'valueText', field: 'allows', valueIndex: i, phase: 'Radici', question: (v) => `Che cosa ti permette di ottenere, sentire o vivere ${v.source || 'questo elemento'}?` },
      { id: `deeper-${i}`, kind: 'valueText', field: 'deeper', valueIndex: i, phase: 'Radici', question: () => 'E questo, che cosa ti dà di ancora più importante?' },
      { id: `final-${i}`, kind: 'finalValue', valueIndex: i, phase: 'Valore-fine' },
    )
  }
  steps.push({ id: 'duplicates', kind: 'duplicates', phase: 'Valori-fine' })
  for (let i = 0; i < 5; i += 1) steps.push({ id: `metrics-${i}`, kind: 'metrics', valueIndex: i, phase: 'Presenza' })
  steps.push({ id: 'ranking', kind: 'ranking', phase: 'Gerarchia' })
  for (let i = 0; i < 4; i += 1) steps.push({ id: `compare-${i}`, kind: 'compare', pairIndex: i, phase: 'Verifica' })
  steps.push({ id: 'hierarchy', kind: 'hierarchy', phase: 'Gerarchia' })
  desireQuestions.forEach(([field, question]) => steps.push({ id: `desire-${field}`, kind: 'text', bucket: 'desire', field, question, phase: 'Desiderio' }))
  for (let i = 0; i < 5; i += 1) steps.push({ id: `compatibility-${i}`, kind: 'compatibility', valueIndex: i, phase: 'Bussola' })
  steps.push({ id: 'compass', kind: 'compass', phase: 'Bussola' })
  const conditionQuestions = [['must', 'Quali condizioni devono essere presenti perché questa scelta sia coerente con te?'], ['negotiable', 'Su quali aspetti sei disposto a trovare un compromesso?'], ['refuse', 'Quali condizioni renderebbero questa scelta incompatibile con la vita che vuoi proteggere?'], ['verify', 'Quali informazioni ti mancano prima di poter decidere?']]
  conditionQuestions.forEach(([field, question]) => steps.push({ id: `condition-${field}`, kind: 'text', bucket: 'conditions', field, question, phase: 'Condizioni' }))
  ecologyQuestions.forEach(([field, question]) => steps.push({ id: `ecology-${field}`, kind: 'text', bucket: 'ecology', field, question, phase: 'Ecologia' }))
  goalQuestions.forEach(([field, question]) => steps.push({ id: `goal-${field}`, kind: 'text', bucket: 'goal', field, question, phase: 'Obiettivo' }))
  solidityQuestions.forEach(([field, question]) => steps.push({ id: `solidity-${field}`, kind: 'solidity', field, question, phase: 'Solidità' }))
  steps.push({ id: 'review', kind: 'review', phase: 'Sintesi' }, { id: 'complete', kind: 'complete', phase: 'Completato' })
  return steps
}
const steps = buildSteps()

function Scale({ label, value, onChange }) {
  return <label className="vgScale"><span>{label}<strong>{value}/10</strong></span><input type="range" min="0" max="10" value={value} onChange={(event) => onChange(Number(event.target.value))} aria-label={`${label}: ${value} su 10`} /></label>
}

function ValueChain({ value }) {
  return <div className="vgChain">{[value.source, value.meaning, value.allows, value.deeper, value.final].filter(Boolean).map((item, index, array) => <React.Fragment key={`${item}-${index}`}><span>{item}</span>{index < array.length - 1 && <ArrowRight />}</React.Fragment>)}</div>
}

function CompassView({ state }) {
  const ordered = state.order.map((index) => ({ ...state.values[index], index })).filter((item) => item.final || item.source)
  const statusClass = (status = '') => status.includes('condizioni') ? 'conditional' : status.includes('conflitto') ? 'conflict' : status.includes('compatibile') ? 'compatible' : 'unknown'
  return <div className="vgCompass" role="img" aria-label="Bussola dei valori e compatibilità con il lavoro desiderato"><div className="vgCompassCenter"><Compass /><small>IL LAVORO DESIDERATO</small><strong>{state.desire.desire || 'La tua direzione professionale'}</strong></div>{ordered.map((value, position) => <article key={value.index} className={`vgCompassPoint p${position + 1} ${statusClass(state.compatibility[value.index]?.status)}`}><b>{position + 1}</b><div><strong>{value.final || value.source || `Valore ${position + 1}`}</strong><small>{state.compatibility[value.index]?.status || 'Da verificare'}</small></div></article>)}</div>
}

export function ValuesGoalWorkbookPage() {
  const [state, setState] = useState(loadState); const [errors, setErrors] = useState({}); const [sending, setSending] = useState(false); const mainRef = useRef(null)
  const stepIndex = Math.min(Math.max(state.step, 0), steps.length - 1); const step = steps[stepIndex]
  useLandingMeta({ title: 'Bussola dei valori e obiettivo | Gabriele Ciandrini', description: 'Percorso riservato della fase Immagina per costruire la gerarchia dei valori e un obiettivo professionale ben formato.', robots: 'noindex, follow' })
  useEffect(() => localStorage.setItem(STORAGE_KEY, JSON.stringify({ ...state, step: stepIndex })), [state, stepIndex])
  const progress = Math.round(stepIndex / (steps.length - 1) * 100)
  const updateValue = (index, patch) => setState((old) => ({ ...old, values: old.values.map((value, i) => i === index ? { ...value, ...patch } : value) }))
  const updateBucket = (bucket, field, value) => setState((old) => ({ ...old, [bucket]: { ...old[bucket], [field]: value } }))
  const goTo = (next) => { setErrors({}); setState((old) => ({ ...old, step: Math.min(Math.max(next, 0), steps.length - 1) })); requestAnimationFrame(() => mainRef.current?.scrollIntoView({ behavior: 'smooth' })) }
  const next = () => goTo(stepIndex + 1); const previous = () => goTo(stepIndex - 1)
  const start = () => { const nextErrors = {}; if (state.name.trim().length < 2) nextErrors.name = 'Scrivi almeno due caratteri.'; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(state.email.trim())) nextErrors.email = 'Inserisci un indirizzo e-mail valido.'; if (!state.privacyAccepted) nextErrors.privacy = 'Conferma di aver letto l’informativa.'; setErrors(nextErrors); if (!Object.keys(nextErrors).length) next() }
  const move = (position, delta) => setState((old) => { const order = [...old.order]; const target = position + delta; if (target < 0 || target >= order.length) return old; [order[position], order[target]] = [order[target], order[position]]; return { ...old, order } })
  const suggest = (index) => commonEnds[cleanWord(state.values[index].source)] || state.values[index].deeper.trim().split(/[,.!?;]/)[0].trim().split(/\s+/).slice(-2).join(' ') || state.values[index].source
  const submit = async () => { setSending(true); setErrors({}); try { const response = await fetch('/api/values-goal-submit', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...state, name: state.name.trim(), email: state.email.trim().toLowerCase(), landingPath: VALUES_GOAL_PATH }) }); if (!response.ok) throw new Error(); localStorage.removeItem(STORAGE_KEY); goTo(steps.length - 1) } catch { setSending(false); setErrors({ submit: 'Invio non riuscito. La bozza è ancora salvata su questo dispositivo: puoi riprovare senza perdere nulla.' }) } }
  const reset = () => { if (window.confirm('Vuoi cancellare la bozza e ricominciare?')) { localStorage.removeItem(STORAGE_KEY); setState(emptyState()); setErrors({}) } }
  const currentValue = step.valueIndex !== undefined ? state.values[step.valueIndex] : null
  const summary = useMemo(() => ({ objective: state.goal.positiveGoal || state.desire.desire || '', meaning: state.desire.attraction || state.desire.allows || '', values: state.order.map((index) => state.values[index].final).filter(Boolean).join(', '), conditions: state.conditions.must || state.goal.requiredConditions || '', refuse: state.conditions.refuse || '', verify: state.conditions.verify || '', evidence: state.goal.evidence || '', resources: state.goal.resources || '', missing: state.goal.missingResources || '', firstStep: state.goal.firstStep || '', date: state.goal.firstStepDate || '', criterion: state.goal.firstStepEvidence || '' }), [state])

  return <div className="valuesGoal" style={{ '--accent': currentValue?.color || '#cbff45' }}>
    <header className="vgHeader"><LandingBrand inverse /><div><button type="button" onClick={reset}><RotateCcw /> Ricomincia</button><a href="/">Esci</a></div></header>
    <div className="vgProgress"><span style={{ width: `${progress}%` }} /><small>{step.phase} · {progress}%</small></div>
    <main ref={mainRef} className="vgMain">
      {step.kind === 'intro' && <section className="vgPanel vgIntro"><p className="vgKicker"><span>IMMAGINA</span> Spazio riservato · da usare durante una seduta individuale</p><h1>La vita professionale che desideri rispetta davvero <em>ciò che conta per te?</em></h1><p className="vgLead">Partiremo da cinque cose importanti nella tua vita. Le esploreremo per scoprire quali valori profondi rappresentano, costruiremo la tua gerarchia personale e la confronteremo con il lavoro che desideri. Non esistono risposte giuste: esiste ciò che per te conta davvero.</p><div className="vgIntroGrid"><div><Save /><strong>La bozza si salva da sola</strong><p>Puoi tornare indietro e modificare ogni risposta.</p></div><div><Mail /><strong>Riceverai un PDF</strong><p>Una copia arriverà anche a Gabriele per proseguire la seduta.</p></div><div><LockKeyhole /><strong>Nessuna diagnosi</strong><p>Evita dati sanitari o particolarmente delicati.</p></div></div><div className="vgIdentity"><label>Nome<input value={state.name} onChange={(e) => setState((old) => ({ ...old, name: e.target.value }))} autoComplete="name" placeholder="Come ti chiami?" />{errors.name && <small>{errors.name}</small>}</label><label>E-mail<input value={state.email} onChange={(e) => setState((old) => ({ ...old, email: e.target.value }))} type="email" autoComplete="email" placeholder="nome@email.it" />{errors.email && <small>{errors.email}</small>}</label><label className="vgHoney">Azienda<input value={state.company} onChange={(e) => setState((old) => ({ ...old, company: e.target.value }))} tabIndex="-1" /></label><label className="vgPrivacy"><input type="checkbox" checked={state.privacyAccepted} onChange={(e) => setState((old) => ({ ...old, privacyAccepted: e.target.checked }))} /><span>Ho letto la <a href={PRIVACY_URL} target="_blank" rel="noreferrer">Privacy Policy</a> e chiedo di ricevere il riepilogo.</span></label>{errors.privacy && <small>{errors.privacy}</small>}</div><button className="vgPrimary" type="button" onClick={start}>Inizia il percorso <ArrowRight /></button></section>}
      {step.kind === 'sources' && <section className="vgPanel"><p className="vgKicker"><span>LE RADICI</span> Cinque punti di partenza</p><h1>Scrivi cinque cose che consideri importanti nella tua vita.</h1><p className="vgHint">Possono essere ambiti, persone, bisogni o condizioni. Non devono essere già “valori”. Per esempio: famiglia, salute, lavoro, libertà, sicurezza, crescita.</p><div className="vgSources">{state.values.map((value, index) => <label key={index} style={{ '--value-color': value.color }}><b>{index + 1}</b><input value={value.source} onChange={(e) => updateValue(index, { source: e.target.value })} placeholder={`Elemento ${index + 1}`} aria-label={`Elemento importante ${index + 1}`} /></label>)}</div></section>}
      {step.kind === 'valueText' && <section className="vgPanel vgQuestion"><p className="vgKicker"><span style={{ background: currentValue.color }}>VALORE {step.valueIndex + 1} DI 5</span> Risposta facoltativa</p><ValueChain value={currentValue} /><h1>{step.question(currentValue)}</h1><textarea autoFocus value={currentValue[step.field]} onChange={(e) => updateValue(step.valueIndex, { [step.field]: e.target.value })} placeholder="Scrivi qui, con parole tue…" maxLength="1800" /><div className="vgQuestionOptions"><button type="button" onClick={next}><Check /> Questo è il valore profondo</button><button type="button" onClick={next}><ArrowDown /> Sento che c’è qualcosa di ancora più profondo</button></div></section>}
      {step.kind === 'finalValue' && <section className="vgPanel vgQuestion"><p className="vgKicker"><span style={{ background: currentValue.color }}>VALORE {step.valueIndex + 1} DI 5</span> La parola la scegli tu</p><ValueChain value={currentValue} /><h1>Dalle tue parole sembra emergere il valore <em>{suggest(step.valueIndex) || '…'}</em>. Ti riconosci in questa parola?</h1><label className="vgFinalInput">Il mio valore-fine<input autoFocus value={currentValue.final} onChange={(e) => updateValue(step.valueIndex, { final: e.target.value })} placeholder={suggest(step.valueIndex) || 'Scrivi la parola che senti tua'} /></label><div className="vgQuestionOptions"><button type="button" onClick={() => { updateValue(step.valueIndex, { final: currentValue.final || suggest(step.valueIndex) }); next() }}><Check /> Sì, mi rappresenta</button><button type="button" onClick={previous}><ArrowLeft /> Voglio tornare alla risposta precedente</button></div></section>}
      {step.kind === 'duplicates' && <section className="vgPanel"><p className="vgKicker"><span>COLLEGAMENTI</span> Nessuna unione automatica</p><h1>Questi valori per te sono distinti, collegati o duplicati?</h1><p className="vgLead">Se due percorsi portano allo stesso valore-fine puoi rinominarne uno. Le origini restano comunque visibili nel riepilogo.</p><div className="vgValueCards">{state.values.map((value, index) => <article key={index} style={{ '--value-color': value.color }}><small>{value.source || `Elemento ${index + 1}`}</small><input value={value.final} onChange={(e) => updateValue(index, { final: e.target.value })} aria-label={`Nome del valore-fine ${index + 1}`} /><ValueChain value={value} /></article>)}</div></section>}
      {step.kind === 'metrics' && <section className="vgPanel"><p className="vgKicker"><span style={{ background: currentValue.color }}>PRESENZA {step.valueIndex + 1} DI 5</span> Una fotografia di oggi</p><h1>Quanto conta e quanto riesci a vivere <em>{currentValue.final || currentValue.source || 'questo valore'}</em>?</h1><div className="vgScales"><Scale label="Importanza nella tua vita" value={currentValue.importance} onChange={(v) => updateValue(step.valueIndex, { importance: v })} /><Scale label="Presenza oggi nella tua vita" value={currentValue.presence} onChange={(v) => updateValue(step.valueIndex, { presence: v })} /><Scale label="Presenza nel lavoro attuale" value={currentValue.workPresence} onChange={(v) => updateValue(step.valueIndex, { workPresence: v })} /></div>{currentValue.importance - currentValue.presence >= 4 && <div className="vgGap"><Sparkles /><p>Questo valore è molto importante, ma oggi sembra poco presente. Non è una diagnosi: è una distanza da esplorare durante la seduta.</p></div>}</section>}
      {step.kind === 'ranking' && <section className="vgPanel"><p className="vgKicker"><span>PRIMO ORDINE</span> Provvisorio</p><h1>Metti i valori nell’ordine che senti più vero in questo momento.</h1><div className="vgRanking">{state.order.map((valueIndex, position) => { const value = state.values[valueIndex]; return <article key={valueIndex} style={{ '--value-color': value.color }}><b>{position + 1}</b><div><strong>{value.final || value.source || `Valore ${valueIndex + 1}`}</strong><small>Importanza {value.importance}/10 · Presenza {value.presence}/10</small></div><span><button type="button" onClick={() => move(position, -1)} disabled={!position} aria-label={`Sposta ${value.final} sopra`}><ArrowUpIcon /></button><button type="button" onClick={() => move(position, 1)} disabled={position === 4} aria-label={`Sposta ${value.final} sotto`}><ArrowDown /></button></span></article> })}</div></section>}
      {step.kind === 'compare' && (() => { const a = state.values[state.order[step.pairIndex]], b = state.values[state.order[step.pairIndex + 1]]; return <section className="vgPanel vgQuestion"><p className="vgKicker"><span>PROVA DI COERENZA</span> Confronto {step.pairIndex + 1} di 4</p><h1>Se potessi proteggere soltanto uno tra <em>{a.final || a.source}</em> e <em>{b.final || b.source}</em>, quale sceglieresti?</h1><p className="vgLead">Pensa anche a cosa hai protetto nella realtà: era ciò che volevi o ciò che in quel momento eri costretto a fare?</p><div className="vgChoiceGrid">{[`Mantengo l’ordine: ${a.final || a.source}`, `Inverto: prima ${b.final || b.source}`, 'Sono sullo stesso livello', 'Uno è necessario per vivere l’altro', 'Voglio rifletterci ancora'].map((option) => <button className={state.comparisons[step.pairIndex] === option ? 'selected' : ''} type="button" key={option} onClick={() => { updateBucket('comparisons', step.pairIndex, option); if (option.startsWith('Inverto')) move(step.pairIndex, 1) }}>{option}</button>)}</div></section> })()}
      {step.kind === 'hierarchy' && <section className="vgPanel"><p className="vgKicker"><span>GERARCHIA</span> La tua bussola</p><h1>Questa classifica rappresenta ciò che vuoi proteggere nelle tue scelte?</h1><div className="vgRanking">{state.order.map((valueIndex, position) => { const value = state.values[valueIndex]; return <article key={valueIndex} style={{ '--value-color': value.color }}><b>{position + 1}</b><div><strong>{value.final || value.source}</strong><small>{value.meaning || 'Definizione ancora aperta'} · importanza {value.importance}/10</small></div><span><button type="button" onClick={() => move(position, -1)} disabled={!position}><ArrowUpIcon /></button><button type="button" onClick={() => move(position, 1)} disabled={position === 4}><ArrowDown /></button></span></article> })}</div></section>}
      {step.kind === 'text' && <section className="vgPanel vgQuestion"><p className="vgKicker"><span>{step.phase.toUpperCase()}</span> Risposta facoltativa</p><h1>{step.question}</h1><textarea autoFocus value={state[step.bucket]?.[step.field] || ''} onChange={(e) => updateBucket(step.bucket, step.field, e.target.value)} placeholder="Scrivi qui, con parole tue…" maxLength="3000" /></section>}
      {step.kind === 'compatibility' && <section className="vgPanel vgQuestion"><p className="vgKicker"><span style={{ background: currentValue.color }}>BUSSOLA {step.valueIndex + 1} DI 5</span> Il sistema suggerisce, tu decidi</p><h1>Quanto è compatibile il lavoro che desideri con <em>{currentValue.final || currentValue.source}</em>?</h1><p className="vgLead">{state.desire.desire ? `Stai valutando: “${state.desire.desire}”.` : 'Se ti mancano informazioni concrete, scegli “Non ho ancora abbastanza informazioni”.'}</p><div className="vgChoiceGrid">{compatibilityOptions.map((option) => <button type="button" className={state.compatibility[step.valueIndex]?.status === option ? 'selected' : ''} key={option} onClick={() => updateBucket('compatibility', step.valueIndex, { ...(state.compatibility[step.valueIndex] || {}), status: option })}>{option}</button>)}</div><label className="vgFollowup">Che cosa dovrebbe essere vero, o quale informazione devi raccogliere?<textarea value={state.compatibility[step.valueIndex]?.note || ''} onChange={(e) => updateBucket('compatibility', step.valueIndex, { ...(state.compatibility[step.valueIndex] || {}), note: e.target.value })} /></label></section>}
      {step.kind === 'compass' && <section className="vgPanel vgCompassPanel"><p className="vgKicker"><span>BUSSOLA DEI VALORI</span> Il progetto al centro, ciò che conta intorno</p><h1>Il futuro che immagini regge il confronto con la vita che vuoi proteggere?</h1><CompassView state={state} /><div className="vgLegend"><span className="compatible">Compatibile</span><span className="conditional">Con condizioni</span><span className="conflict">In conflitto</span><span className="unknown">Da verificare</span></div></section>}
      {step.kind === 'solidity' && <section className="vgPanel"><p className="vgKicker"><span>SOLIDITÀ</span> Un voto non è un giudizio</p><h1>{step.question}</h1><Scale label={step.question} value={state.solidity[step.field] ?? 7} onChange={(v) => updateBucket('solidity', step.field, v)} />{(state.solidity[step.field] ?? 7) < 8 && <label className="vgFollowup">Che cosa dovrebbe cambiare per portare questo voto almeno a 8?<textarea value={state.improve[step.field] || ''} onChange={(e) => updateBucket('improve', step.field, e.target.value)} /></label>}</section>}
      {step.kind === 'review' && <section className="vgPanel vgReview"><p className="vgKicker"><span>SINTESI FINALE</span> Ogni sezione può ancora essere modificata</p><h1>{firstName(state.name)}, la tua direzione ora ha <em>radici e condizioni.</em></h1><CompassView state={state} /><div className="vgSummary"><p><strong>Voglio ottenere</strong> {summary.objective || '—'}</p><p><strong>Per me è importante perché</strong> {summary.meaning || '—'}</p><p><strong>È coerente con</strong> {summary.values || '—'}</p><p><strong>Devono essere rispettate</strong> {summary.conditions || '—'}</p><p><strong>Non sono disposto ad accettare</strong> {summary.refuse || '—'}</p><p><strong>Devo ancora verificare</strong> {summary.verify || '—'}</p><p><strong>Saprò di averlo raggiunto quando</strong> {summary.evidence || '—'}</p><p><strong>Possiedo già</strong> {summary.resources || '—'}</p><p><strong>Devo sviluppare o trovare</strong> {summary.missing || '—'}</p><p><strong>Il mio primo passo sarà</strong> {summary.firstStep || '—'}</p><p><strong>Lo farò entro</strong> {summary.date || '—'}</p><p><strong>Verificherò il risultato attraverso</strong> {summary.criterion || '—'}</p></div><div className="vgSend"><Mail /><div><small>CONSEGNA PERSONALE</small><h2>Invia il PDF a {state.email}</h2><p>La stessa copia arriverà a Gabriele. La bozza verrà cancellata soltanto dopo l’invio riuscito.</p></div><button className="vgPrimary" type="button" onClick={submit} disabled={sending}>{sending ? 'Invio in corso…' : 'Genera e invia il PDF'} <Send /></button></div>{errors.submit && <p className="vgError">{errors.submit}</p>}</section>}
      {step.kind === 'complete' && <section className="vgPanel vgComplete"><p className="vgKicker"><span>COMPLETATO</span> PDF inviato</p><h1>La tua bussola è pronta. <em>Ora può guidare una scelta concreta.</em></h1><p className="vgLead">Controlla la tua e-mail. Gabriele ha ricevuto la stessa copia per continuare il lavoro durante la seduta.</p><div><a className="vgPrimary" href="/proposta-percorso/">Scopri il percorso Respira. Immagina. Agisci. <ArrowRight /></a><a href="/metodo-respira-immagina-agisci/">Conosci il metodo</a></div></section>}
    </main>
    {stepIndex > 0 && step.kind !== 'complete' && <nav className="vgNav"><button type="button" onClick={previous}><ArrowLeft /> Indietro</button><span><Save /> Salvato sul dispositivo</span>{step.kind !== 'review' && <button className="vgPrimary" type="button" onClick={next}>Avanti <ArrowRight /></button>}</nav>}
    <footer className="vgFooter"><span>Respira. Immagina. Agisci.</span><div><a href="/proposta-percorso/">La proposta</a><a href="/metodo-respira-immagina-agisci/">Il metodo</a><a href={PRIVACY_URL}>Privacy</a></div></footer>
  </div>
}

function ArrowUpIcon() { return <ArrowDown style={{ transform: 'rotate(180deg)' }} /> }
